spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/push
      username: push_admin
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-test-query: select 1
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    ssl: false
    timeout: 3s
    # default settings
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    initialize-schema: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


# program properties
etl:
  tableName:
    spread: tb_autopush_interface_spread
    inform: tb_autopush_interface_inform

---
spring:
  profiles: dev
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    ssl: false
    timeout: 3s
    # default settings
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/push
      username: push_admin
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-test-query: select 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE